<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-GBKDVHB5" failures="1" tests="2" name="Testrunner-1" time="13.389" errors="0" timestamp="2021-09-15T15:36:43 IST">
  <testcase classname="tyss.vtiger.test.DemoTestNG" name="test1" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tyss.vtiger.test.DemoTestNG.test1(DemoTestNG.java:18)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="tyss.vtiger.test.DemoTestNG" name="test2" time="0.007"/>
  <testcase classname="tyss.vtiger.test.DemoTestNG" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Testrunner-1 -->
